### ISSUE TITLE
Invalid requests when password contains some special characters

### ISSUE THREAD

**Issue by neomilium** [theforeman/foreman_fog_proxmox#64] opened 2019-03-15 13:28 UTC
**Describe the bug**
Can not create hosts through Foreman when Proxmox password contains special characters.

**To Reproduce**
1. Setup a user (e.g. `hello@pve`) with password like `pmvu[dE&Cd%dnk5T` on Proxmox
2. Setup compute resource to use these credentials on Foreman
3. Go to `New host` on Foreman
4. Select the Proxmoc compute resource
5. Then, in `Virtual machine` tab, we can see:
```
Failure: Expected([200, 204]) <=> Actual(400 Bad Request) excon.error.response :body => "{\"data\":null,\"errors\":{\"Cd%dnk5T\":\"property is not defined in schema and the schema does not allow additional properties\"}}" :cookies => [ ] :headers => { "Cache-Control" => "max-age=0" "Connection" => "close" "Content-Length" => "123" "Content-Type" => "application/json;charset=UTF-8" "Date" => "Fri, 15 Mar 2019 13:12:04 GMT" "Expires" => "Fri, 15 Mar 2019 13:12:04 GMT" "Pragma" => "no-cache" "Server" => "pve-api-daemon/3.0" } :host => "10.105.42.1" :local_address => "10.105.42.10" :local_port => 48748 :path => "/api2/json/access/ticket" :port => 8006 :reason_phrase => "Parameter verification failed." :remote_ip => "10.105.42.1" :status => 400 :status_line => "HTTP/1.1 400 Parameter verification failed.\r\n" 
```

Note: in this error, we can see a part of the password as the wrong property.

**Expected behavior**
List virtual machine parameters.

**Comment by Yamakasi** [comment] 2019-03-15 23:38
duplicate of #60

**Comment by neomilium** [comment] 2019-03-16 20:03
@Yamakasi I dont think its a duplicate of #60 : I just change the password and now all is working fine.

As you can see in error you can find a part of password in error:
`\"errors\":{\"Cd%dnk5T\":\"property is not defined` does exactly contain all password characters after `&` symbol: `Cd%dnk5T`.

**Comment by Yamakasi** [comment] 2019-03-17 14:28
@neomilium Could be some escape issue indeed.

**Closed** 2019-11-07 15:49 UTC
Labels: bug
